#!/bin/bash
echo "LAB 3 - Copiar, renombrar, borrar archivos"
echo "Ingreso el comando de acuerdo a la instrucción"
echo -e "Si el comando es correcto se mostrará el output\n"

while true
do
        echo "1. Despliega en pantalla el uso del disco de la carpeta actual"
        read comando1
        if [ $comando1 = "du" ]
        then
                $comando1;
                break;
fi
done
while true
do
        echo "2. Despliega en pantalla el uso del disco de la carpeta actual en un formato legible"
        read comando2
        if [[ $comando2 = "duxh" ]]
        then
                du -xh;
                break;
fi
done
echo -e "\n Este comando podría tardar en carpetas de gran tamaño, asi que puedes optar por el parametro --max-depth du --max-depth 3 ~\n"

while true
do
        echo "3. Copia el archivo hello.txt a la carpeta dir2 usando el parametro verbose"
        read comando3
        if [[ $comando3 = "cp -v hello.txt dir2" ]]
        then
                $comando3;
                break;
fi
done
while true
do
        echo "4. Copia y renombra el archivo hello.txt a dir2/file2.txt usando el parametro verbose"
        read comando4
        if [[ $comando4 = "cp -v hello.txt dir2/file2.txt" ]]
        then
                $comando4;
                break;
fi
done
while true
do
 echo "5. Copia todos los archivos con la extensión .txt de la carpeta dir2 a la carpeta dir2/dir3"
        read comando5
        if [[ $comando5 = "cp -vr dir2/*.txt dir2/dir3" ]]
        then
                $comando5;
                break;
fi
done
while true
do
        echo "6. Copia la carpeta dir2/dir3 al directorio actual"
        read comando6
        if [[ $comando6 = "cp -vr dir2/dir3 ." ]]
        then
                $comando6;
                break;
fi
done
while true
do
        echo "7. Muestra el contenido de la carpeta actual"
        read comando7;
        if [ $comando7 = "ls" ]
        then
                $comando7;
                break;
fi
done
while true
do
        echo "8. Verifica la integridad de los archivo copiado hello.txt"
        read comando8
        read comando9
        if [[ $comando8 = "md5sum hello.txt" && $comando9 = "md5sum dir2/hello.txt" ]]
        then
                $comando8;
                $comando9;
                break;
fi
done
while true
do
        echo "9. Mueve el archivo hello.txt a dir2/dir3/dir4/hi.txt"
        read comando10
        if [[ $comando10 = "mv hello.txt dir2/dir3/dir4/hi.txt" ]]
        then
                $comando10;
                break;
fi
done
while true
do
        echo "10. Muestra el contenido de la carpeta dir4 desde dir2"
        read comando11
        if [[ $comando11 = "ls dir2/dir3/dir4" ]]
        then
                $comando11;
                break;
fi
done
while true
do
        echo "11. Crear la carpeta dir5"
        read comando12
        if [[ $comando12 = "mkdir dir5" ]]
        then
                $comando12;
                break;
fi
done
while true
do
        echo "12. Mueve todos los archivos de texto en dir2 hacia dir5"
        read comando13
        if [[ $comando13 = "mv dir2/*.txt dir5" ]]
        then
                $comando13;
                break;
fi
done
while true
do
        echo "13. Renombra la carpeta dir5 a dir50"
        read comando14
        if [[ $comando14 = "mv dir5 dir50" ]]
        then
                $comando14;
                break;
fi
done
while true
do
        echo "14. Crea un enlace llamado \"hello\" desde el directorio actual hacia dir2/dir3/dir4/hi.txt"
        read comando15
        if [[ $comando15 = "ln dir2/dir3/dir4/hi.txt hello" ]]
        then
                $comando15;
                break;
                fi
done
while true
do
        echo "16. Elimina el archivo file2.txt de forma interactiva"
        read comando17
        if [[ $comando17 = "rm -i file2.txt" ]]
        then
                $comando17;
                break;
fi
done
while true
do
        echo "17. Elimina de forma interactiva y recursiva el contenido de dir5"
        read comando18
        if [[ $comando18 = "rm -ir dir50/*" ]]
        then
          $comando18;
           break;
        fi
done
                                             
                                                                                
